language: scala
scala:
- 2.10.5
- 2.11.7
cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.sbt
  - $HOME/.ivy2
jdk:
- oraclejdk8
- oraclejdk7
- openjdk6
branches:
  only:
  - master
services:
- mysql
- postgresql
addons:
  postgresql: "9.3"

before_script:
  - psql -c 'create database myapp_test;' -U postgres

script: sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport coverageAggregate +publish
after_success:
  - sbt coveralls

after_script:
  - psql -c 'drop database myapp_test;' -U postgres

env:
  global:
  - secure: i/BvVZrhW7k0Q7JtQqlSEMnw6HXTZei5TCNTearwq0W4b4S3S6bQnJSjgzuPsj0aTieU+MBlglINae2pJuEYHlypw7twt6ua+4yhavDmxiMKio11dJAGOYHTNW+thj+VNo3qf0YORWBU+Mu2xZeI+RiUT77TPjc//PzE0dCuW4VzhFZrXsO0egKn08ZJiM6fAZDI91ThgfdP7NIJgxVR7DzNU8Eb/2jGGC2ZLD7NtMRqCFuL53IdC2rf1eTuELEWhYQzEmpydReKJeU0swCx7jT3YndqSsWYZVo8NmprGzwfbB7kbkT67UVI6zvbF0HTXHg1ByJyuBMARAPWR1zzLkCJPkakrknUqtnF8Z0kqRQrpg1fFfOIKrYGcVvHXiKcAp29Vzw12lsmjqrJawjWOwxPplXMlZvNgdtDYOxEFqe6kDxMT3rhOuP+J7WR+KwSYPaTn70NM8Ng1kTvzeILx0+p6kkrAuX09myWBpBbpZ8mT92DWA5i10zvB1psOJaLLgwxq1aTGmaxpnuAFwXAN40lk0bAxlT57C1L2ZS6/ZU42+WHm5cXTB9BWQhItK7PcALIdLRSISk1PvyDYKeK4N8TCVRxBnCxlTVZhBV3pAbdl4PoyFEtlphfKPDc9HXgLnuTS31hzrawwPl/m1vPiu+enLEOIw882BDxaZj2Lng=
  - secure: Ro2Ao+zjcu+Xqcob6+fya4Tn6vKI19elafSz5LmQ4eITTTgIlrPpd9fdh55fIePV8by868bQpJTKZ8mZYJEXbaFCB+HOtqyM1JIFkoEP5WDZKsnX/siSEb2Y3I7tDJcgGdl0qkAFVYlwwDnqnG08HXH7W4BCYVrBFUPo6D9PJ6ZaPG21k5M5+x9nwJi9NF0TdzEhomMFtzBbqCh8z+3mwwIdsQ8rJfXkVHduVYHCBZ0qJvhoaO3QL7I1MKQJldfQDVYjKhQqDgHh4iZHaDFS+gm/ki7DickaFTsYJya/VjCF8L9kxyXmxg/Fa9nGVtx/jzI2VH+DATFetCEMxNY2t+9WLU77dJvFCmJU7Y01tsYiS3REw6yRgp8I9nH6sINQmErADslcbZdYTcyiZn6opoonaLIBtOdVogqlEC6RXwPy7KAeHHgD9tpdlInR2J4mb11FkiKc9dYAGSrEvx6atc9RnH/14mW2tZM8WUJIWzEJrLX1H9KKQrQGpHCNVdfrO+fWtlFYU8gYvArU8RyKEt33zl9ts/6wD1pAkpy60hj2FpFdt32OhTsGZwJD6Y7vmHue2BFEzEi7CyywV7iGgnBwLOIXQPNy1wbtJbOYJ3P/pONPFleBBLXotNBhCcJP94Uxxe4qwlJM52c5SjHtvJAPWbjltujzy8UgUqYdTu4=
  - secure: obemDmqU19Vu+yc00i1Kok8/5w0Em8ZJRCBXMMCZTAkyJtp85dYzNiAszwIdtQyCdqZO5m8bycy493gCSAl1Rdji/mu4rSREwHhCbzBfmPLH+qPVkTNB1YrZYq9avyPDFXW0/1w4ATefujurYcifxXR7Y2WaiekC70gVipEdm+RDdQg8o7G5Vg5tAMgxF+cIMDk5jvMdNd2cQVJekclZZS4G9gba/LIxWQQhn+ipHYwIw5J+37mA7AbSIlKFVxYnnfBzXn3HVzSIou2+K3zCef8tLsakmJMCeOQmaNcehJMRvO5nfEmU1mCOL4kKZtXf0SSLVo9QB6/lN8dMkR75Mk6Wq6MhCk6Huc/oHvwzbawg2rPW63br3rZ3zFhP/CAHcS1i5JKAjPyJJdtTorN+SMX0D/HtXDR2ExrQVaBc7agRihkBy1Wdm4CU83E1DBnt+9VKUSyemEKBQpWW/LRJoV7WKwGSFxwhdTbKNYawdP+XDsSX2mQKg/A5Y29ooQCRIJomhnLPGXUDjgsJ3R6BSNE9wWXEC6EzmjIDTA/tT/KGTnUd9W7SzxSYKUOlVrp1iBXmLc7/H3YljX8+PVxCo/RJv23QKRfQX4DKGVOq+/c4+Rz2VKBD/Ye4pqskTq6mpbfKf0S1scRkijpbVjA2aczNgHVtdDfUEvpXUVF70bI=
