language: scala
scala:
- 2.10.5
- 2.11.7
cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.sbt
  - $HOME/.ivy2
jdk:
- oraclejdk8
- oraclejdk7
- openjdk6
branches:
  only:
  - master
services:
- mysql
before_script:
- mysql -e "create database IF NOT EXISTS myapp_test;" -uroot
after_script:
- mysql -e "drop database myapp_test;" -uroot
script: sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageAggregate +publish
env:
  global:
  - secure: i/BvVZrhW7k0Q7JtQqlSEMnw6HXTZei5TCNTearwq0W4b4S3S6bQnJSjgzuPsj0aTieU+MBlglINae2pJuEYHlypw7twt6ua+4yhavDmxiMKio11dJAGOYHTNW+thj+VNo3qf0YORWBU+Mu2xZeI+RiUT77TPjc//PzE0dCuW4VzhFZrXsO0egKn08ZJiM6fAZDI91ThgfdP7NIJgxVR7DzNU8Eb/2jGGC2ZLD7NtMRqCFuL53IdC2rf1eTuELEWhYQzEmpydReKJeU0swCx7jT3YndqSsWYZVo8NmprGzwfbB7kbkT67UVI6zvbF0HTXHg1ByJyuBMARAPWR1zzLkCJPkakrknUqtnF8Z0kqRQrpg1fFfOIKrYGcVvHXiKcAp29Vzw12lsmjqrJawjWOwxPplXMlZvNgdtDYOxEFqe6kDxMT3rhOuP+J7WR+KwSYPaTn70NM8Ng1kTvzeILx0+p6kkrAuX09myWBpBbpZ8mT92DWA5i10zvB1psOJaLLgwxq1aTGmaxpnuAFwXAN40lk0bAxlT57C1L2ZS6/ZU42+WHm5cXTB9BWQhItK7PcALIdLRSISk1PvyDYKeK4N8TCVRxBnCxlTVZhBV3pAbdl4PoyFEtlphfKPDc9HXgLnuTS31hzrawwPl/m1vPiu+enLEOIw882BDxaZj2Lng=
  - secure: Ro2Ao+zjcu+Xqcob6+fya4Tn6vKI19elafSz5LmQ4eITTTgIlrPpd9fdh55fIePV8by868bQpJTKZ8mZYJEXbaFCB+HOtqyM1JIFkoEP5WDZKsnX/siSEb2Y3I7tDJcgGdl0qkAFVYlwwDnqnG08HXH7W4BCYVrBFUPo6D9PJ6ZaPG21k5M5+x9nwJi9NF0TdzEhomMFtzBbqCh8z+3mwwIdsQ8rJfXkVHduVYHCBZ0qJvhoaO3QL7I1MKQJldfQDVYjKhQqDgHh4iZHaDFS+gm/ki7DickaFTsYJya/VjCF8L9kxyXmxg/Fa9nGVtx/jzI2VH+DATFetCEMxNY2t+9WLU77dJvFCmJU7Y01tsYiS3REw6yRgp8I9nH6sINQmErADslcbZdYTcyiZn6opoonaLIBtOdVogqlEC6RXwPy7KAeHHgD9tpdlInR2J4mb11FkiKc9dYAGSrEvx6atc9RnH/14mW2tZM8WUJIWzEJrLX1H9KKQrQGpHCNVdfrO+fWtlFYU8gYvArU8RyKEt33zl9ts/6wD1pAkpy60hj2FpFdt32OhTsGZwJD6Y7vmHue2BFEzEi7CyywV7iGgnBwLOIXQPNy1wbtJbOYJ3P/pONPFleBBLXotNBhCcJP94Uxxe4qwlJM52c5SjHtvJAPWbjltujzy8UgUqYdTu4=
