package slick.migration.dialect

import slick.migration.ast.ColumnInfo

import scala.slick.driver.HsqldbDriver

/**
 * Created by Iliya Tryapitsin on 20/01/15.
 */
class HsqldbDialect(driver: HsqldbDriver) extends Dialect[HsqldbDriver](driver) {
  override def autoInc(ci: ColumnInfo) =
    if (ci.autoInc) " GENERATED BY DEFAULT AS IDENTITY" else ""

  override def primaryKey(ci: ColumnInfo, newTable: Boolean) =
    autoInc(ci) + (if (newTable && ci.isPk) " PRIMARY KEY" else "")

  override def notNull(ci: ColumnInfo) =
    if (ci.notNull && !ci.isPk) " NOT NULL" else ""
}
